site_name: pyliblo3
theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections

extra_css:
  - stylesheets/extra.css
      
markdown_extensions:
    - toc:
        toc_depth: 3
    - pymdownx.highlight
    - pymdownx.superfences
    - admonition

use_directory_urls: false

repo_url: https://github.com/gesellkammer/pyliblo3

nav:
    - index.md 
    - Reference.md
    
