name: Build

on: [push, pull_request]

# on: create 

jobs:
  build_wheels:
    name: Build python wheels on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macOS-10.15, windows-2019]
        # os: [windows-2019]
        os: [macOS-10.15, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
   
      - name: Install dependencies macos
        if: runner.os == 'macos'
        run: |
            brew install liblo
            
      - name: Windows - Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.7.0    

      - name: Install dependencies windows
        if: runner.os == 'windows'
        run: |
            git clone https://github.com/radarsat1/liblo
            cd liblo
            mkdir build
            cd build
            cmake ../cmake
            cmake --build .
            cmake --install .

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        # to supply options, put them in 'env', like:
        env:
            CIBW_BUILD: 'cp39-* cp310-* cp311-*'
            CIBW_ARCHS_MACOS: 'x86_64 arm64'            
            CIBW_SKIP: 'pp* *686* *-musllinux_*'
            CIBW_BEFORE_ALL_LINUX: yum install -y liblo-devel

      # CIBW_SOME_OPTION: value
            
      - uses: actions/upload-artifact@v3
        with:
            path: ./wheelhouse/*.whl

      - name: Upload wheels
        env:
            # TWINE_USERNAME: __token__
            TWINE_USERNAME: Eduardo.Moguillansky
            TWINE_PASSWORD: ${{ secrets.pypipass }}
        run: |
            echo $TWINE_USERNAME
            echo $TWINE_PASSWORD
            python -m pip install -U twine virtualenv
            twine upload --skip-existing wheelhouse/*.whl
        continue-on-error: true

